language: python
sudo: false
dist: trusty
addons:
  firefox: latest
cache:
  directories:
    - $HOME/.npm
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start || true
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install -c conda-forge mamba
  - mamba install -c conda-forge nodejs=13 matplotlib
  - mamba install jupyterlab=3 ipywidgets jupyterlab_widgets -c conda-forge/label/jupyterlab_rc -c conda-forge/label/jupyterlab_server_rc -c conda-forge/label/jupyterlab_widgets_rc -c conda-forge
  - pip install .
script:
  - test -d $HOME/miniconda/share/jupyter/nbextensions/jupyter-matplotlib
  - test -f $HOME/miniconda/share/jupyter/nbextensions/jupyter-matplotlib/extension.js
  - test -f $HOME/miniconda/share/jupyter/nbextensions/jupyter-matplotlib/index.js
  - test -d $HOME/miniconda/share/jupyter/labextensions/jupyter-matplotlib
  - test -f $HOME/miniconda/share/jupyter/labextensions/jupyter-matplotlib/package.json
  - jupyter labextension list 2>&1 | grep -q jupyter-matplotlib
  - python -m jupyterlab.browser_check --NotebookApp.ip=127.0.0.1
